{{- if and .Values.tarpit.secret (not .Values.tarpit.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scale0.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scale0.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.tarpit.secretKey }}: {{ .Values.tarpit.secret | b64enc | quote }}
{{- end }}
