apiVersion: v1
kind: Service
metadata:
  name: gateway-app
  namespace: gateway-app
  labels:
    app: gateway-app
    # scale0 opt-in labels
    scale0/enabled: "true"
    scale0/scale-in-after: "3600"  # scale down after 1 hour
spec:
  selector:
    app: gateway-app
  ports:
    - port: 80
      targetPort: 80
      name: http
